apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-db-deployment
  labels:
    app: my-hm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-db-deployment
  strategy:
    type: Recreate
  template:
    metadata: 
      name: my-hm-db
      labels:
        app: hotel-db-deployment
    spec:
        containers:
          - name: my-db-container
            image: mysql:5.6
            env:
              - name: MYSQL_ROOT_PASSWORD 
                valueFrom:
                  secretKeyRef:
                    name: hm-db-secret
                    key: db-password
            ports:
              - containerPort: 3306 
                name: my-db-container 
            volumeMounts:
            - name: mysql-persistent-volume  
              mountPath: /var/lib/mysql 
            - name: hm-dbscript 
              mountPath: /docker-entrypoint-initdb.d 
        volumes: #the name of the volume and the mount will be same
          - name: mysql-persistent-volume 
            persistentVolumeClaim:
            #mapped to pvc claim we created earlier
              claimName: hm-data-pvc
          - name: hm-dbscript
            configMap: 
              name: db-creation-script

