apiVersion: v1
kind: PersistentVolume
metadata:
  name: hm-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: nodestorage
  hostPath:
    path: /mnt/data
