apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-hm-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: nodestorage
  hostPath:
    path: /hotel/data
